version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
