services:
  #Tên controllers
  app:
    # Tên image
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    
    # Xét thư mục app làm root
    working_dir: /app
    # Ánh xạ ổ đĩa app
    volumes:
      - ./:/app
    
    # Biến môi trường
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  
  #Tên controllers
  mysql:
    # Thêm mysql
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    # Thêm port cho MySQL
    ports:
      - 33063:3306
    # Biến môi trường
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
volumes:
  todo-mysql-data: