version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=myapp
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=mysecretpassword
